---
- name: ubuntu stuff
  include_tasks: ubuntu.yaml
  when:
    ansible_distribution == 'Ubuntu'
- name: centos stuff
  include_tasks: windows.yaml
  when:
    ansible_distribution == 'Microsoft Windows Server 2019 Datacenter'
