---
- hosts: win
  tasks: 
    - name: update firewall rule
      win_firewall_rule:
        localport: 8081
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes
        name: Rule By Ansible
