---
- hosts: lab
  tasks:
    - name: isntall apache2
      apt:
        update_cache: true
        name: apache2
        state: present
    - name: ensure it is running
      service:
        name: apache2
        state: started
    - name: copy a file
      copy:
        src: somefile
        dest: /var/www/html/index.html
