---
- hosts: lab
  tasks:
    - name: update repo list & install prereq
      apt:
        update_cache: true
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
        state: present
    - name: add key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: add repopath
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: install docker
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
