---
- hosts: lab
  vars:
    userdetail:
      name: thinknyx
      dir: /home/testing
  tasks:
    - name: create a user
      user:
        name: "{{ userdetail['name'] }}"
        home: "{{ userdetail['dir'] }}"
        state: present
